### ISSUE TITLE
Create a bibtex entry and add it to the README

### ISSUE THREAD

**Issue by jloehel** [jloehel/molden_modifier#8]
We need to provide a easy way to cite the project. Something like this should do it:

```
@misc{xyz,
    author       = {Alba Vargas},
    title        = {{How to organize your molden files}},
    month        = mar,
    year         = 2020,
    doi          = {xxx},
    version      = {1.0},
    publisher    = {xxx},
    url          = {xxx}
    }
```

Interesting links:
- https://github.com/AASJournals/Tutorials/blob/master/Repositories/CitingRepositories.md
- https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/referencing-and-citing-content

**Comment by alba-vcl** [comment]
@Misc{,
  author = {Juergen Loehel and Alba Vargas-Caamal},
  note   = {name_org},
  title  = {Molden-modifier 1.0},
  year   = {2020},
  url    = {xxx},
}
